### ISSUE TITLE
Error in your vimrc file

### ISSUE THREAD

**Issue by jkemp814** [iambw/vimrc#2]
Hello, I read your article on freecodecamp.org and was impressed.

However, I kept getting an error when I would start Vim. At line 117 it complained about quotes.

This is the line at 117:

" Set the backslash as the leader key.
let mapleader = "\"

I changed that to single quotes and the error went away.

let mapleader = '\'

My understanding is double quotes work like commenting out, right?

https://www.freecodecamp.org/news/vimrc-configuration-guide-customize-your-vim-editor/

**Comment by brandon-wallace** [comment]
In the article I see `mapleader` set to the backslash character. Could it be the backslash character did not display correctly in the browser?

`let mapleader = "\"`

Yes, double quotes are used to make comments. Thank you for reading my article!
